kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-team-api-disk
  namespace: analytics
  labels:
    app: data-team-api-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi